# Copyright (c) JAAK-IT SAPI DE CV - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Javier Moya <javier.moya@jaak-it.com>, 2021.
# Support <support@jaak-it.com>

branches:
  - master

  - name: staging
    prerelease: beta

  - name: develop
    prerelease: dev

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/git"
